### ISSUE TITLE
Annotator fails when a Fix targeting an element in a generated code is suggested.

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/NullAwayAnnotator#27]
**Describe the bug**
In the process of measuring effectiveness of fixes, if a fix is targeting an element in the generated code, `Injector` will throw an exception that it could not find the class which does not exist.

**To Reproduce**
Use a `lombok` builder and target a method in the `builder` class.

**Expected behavior**
`Injector` should report these classes silently when the class is not found and should not terminate the process.

**Screenshots**
Not-Applicable.

**Additional context**
No Additional Context.

**Comment by lazaroclapp** [comment]
Btw, in certain cases, e.g. `Lombok`, we know that the code is generated as it will be within the scope of a `lombok.Generated` annotation, and we could encode that when dumping data from NullAway or Scanner. That said, for now, the more general approach of detecting when we can't modify the source and skipping is probably the better first step. In the future, we might want to detect generated code and consider those errors non-actionable (but still count them towards the tool's "effect").
